services:
  - type: web
    name: cloudpet-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CLOUD_MODE
        value: true
      - key: APP_SECRET_KEY
        generateValue: true