services:
  - type: web
    name: cloudpet-monitor
    env: python
    pythonVersion: "3.10"  # 👈 Explicitly set Python version to 3.10
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CLOUD_MODE
        value: true
      - key: APP_SECRET_KEY
        generateValue: true
